ALTER TABLE public.proposal_items
ADD COLUMN IF NOT EXISTS gross_total NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount_amount NUMERIC NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS net_total NUMERIC NOT NULL DEFAULT 0;